# Generated by Django 5.1.7 on 2025-03-14 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("88fa3a01-55bb-40d7-b8a8-90c98b90c750"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", 1), ("COMPLETED", 2)],
                        default=1,
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "managed": True,
            },
        ),
    ]
