# Generated by Django 5.1.7 on 2025-03-14 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                default=uuid.UUID("79f953dc-8c01-42dd-8dd9-bd2246fb3612"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
