# Generated by Django 5.1.7 on 2025-03-14 20:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
